# Load the required gems/libraries.
require 'active_record'
require 'logger'

# Load all of our ActiveRecord::Base objects.
load 'app/models/log_entry.rb'

# Establish our connection to our serverless sqlite3 database.
ActiveRecord::Base.establish_connection :adapter => 'sqlite3', :database => 'db/development.sqlite3'

# For debugging purposes, uncomment this line to see the SQL generated by ActiveRecord:
# ActiveRecord::Base.logger = Logger.new(STDOUT)

# Uncomment this line to make the logger output look nicer in Windows.
# ActiveSupport::LogSubscriber.colorize_logging = false

ActiveRecord::Schema.define do
  unless ActiveRecord::Base.connection.tables.include? 'log_entries'
    create_table :log_entries do |table|
      table.column :client_ip,        :string
      table.column :client_identd,    :string
      table.column :client_userid,    :string
      table.column :server_time,      :string
      table.column :client_request,   :string
      table.column :status_code,      :integer
      table.column :size_returned,    :integer
      table.column :referrer,         :string
      table.column :client_user_agent,:string
    end
  end
end